name: chat_online
description: Chat Firebase


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9+4
  google_sign_in: ^4.0.7
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+4
  flutter_launcher_icons: ^0.7.3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true




flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"